const BASEURL = process.env.REACT_APP_ENDPOINT
const OPENAI_API_KEY = process.env.REACT_APP_OPENAI_API_KEY
const STREAMENDPOINT = process.env.REACT_APP_STREAMENDPOINT
export {BASEURL, OPENAI_API_KEY, STREAMENDPOINT};